from __future__ import annotations

from typing import List


def validate_form(
    patient_name: str,
    age: str,
    medicine_name: str,
    dosage: str,
    frequency: str,
    food_relation: str,
    duration: str,
    medical_condition: str,
) -> List[str]:
    """Validate the prescription form fields and return error messages."""
    errors: List[str] = []

    if not patient_name.strip():
        errors.append("Patient name is required.")

    if not age.strip():
        errors.append("Age is required.")
    else:
        try:
            age_value = int(age)
        except ValueError:
            errors.append("Age must be a valid whole number.")
        else:
            if age_value < 1 or age_value > 120:
                errors.append("Age must be between 1 and 120.")

    if not medicine_name.strip():
        errors.append("Medicine name is required.")

    if not dosage.strip():
        errors.append("Dosage is required.")

    if not frequency.strip():
        errors.append("Frequency is required.")

    if not food_relation.strip():
        errors.append("Please select before or after food.")

    if not duration.strip():
        errors.append("Duration is required.")
    else:
        try:
            duration_value = int(duration)
        except ValueError:
            errors.append("Duration must be a valid whole number of days.")
        else:
            if duration_value <= 0:
                errors.append("Duration must be greater than zero.")

    if not medical_condition.strip():
        errors.append("Medical condition is required.")

    return errors


def build_summary_text(
    patient_name: str,
    medicine_name: str,
    dosage: str,
    frequency: str,
    duration: str,
    purpose: str,
) -> str:
    """Create a simple, printable prescription summary."""
    lines = [
        "ElderCare AI Prescription Summary",
        "===============================",
        f"Patient Name: {patient_name}",
        f"Medicine: {medicine_name}",
        f"Dosage: {dosage}",
        f"Timing: {frequency}",
        f"Duration: {duration} days",
        f"Purpose: {purpose}",
        "",
        "Generated by ElderCare AI",
    ]
    return "\n".join(lines)
